name: Python Workflow
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Notify on pull request with "Modify code" message
      if: github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'Modify code')
      run: |
        DISCORD_WEBHOOK_URL="<DISCORD_WEBHOOK_URL>"
        curl -X POST -H "Content-Type: application/json" -d '{"content": "Pull request with \"Modify code\" message created: '${{ github.event.pull_request.html_url }}'"}' $DISCORD_WEBHOOK_URL
